#!/bin/bash

xsetroot -cursor_name left_ptr
sxhkd &

bspc config border_width 3
bspc config window_gap 3

bspc config split_ratio 0.5
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1

# bspc config automatic_scheme spiral

for m in $(bspc query -M --names); do
	bspc monitor $m -d 1 2 3 4 5 6 7 9
done
