require("hyprland/variables")
require("hyprland/devices")
require("hyprland/startup")
require("hyprland/keybinds")
require("hyprland/config")
require("hyprland/plugins")
require("monitors")
require("workspaces")
