-- Generated by nwg-displays on 2026-05-31 at 22:01:36. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "1920x1080@239.76",
    position = "1920x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@74.99",
    position = "0x0",
    scale = 1.0
})
