return {
    "nvimdev/dashboard-nvim",
    event = "VimEnter",
    config = function()
        require("dashboard").setup({
            theme = "doom",
            shortcut_type = "letter",
            config = {
                header = {
                    [[                                 ]],
                    [[                                 ]],
                    [[                                 ]],
                    [[                                 ]],
                    [[                                 ]],
                    [[                                 ]],
                    [[                                 ]],
                    [[                                 ]],
                    [[⣴⣶⣤⡤⠦⣤⣀⣤⠆     ⣈⣭⣭⣿⣶⣿⣦⣼⣆          ]],
                    [[   ⠉⠻⢿⣿⠿⣿⣿⣶⣦⠤⠄⡠⢾⣿⣿⡿⠋⠉⠉⠻⣿⣿⡛⣦      ]],
                    [[         ⠈⢿⣿⣟⠦ ⣾⣿⣿⣷⠄⠄⠄⠄⠻⠿⢿⣿⣧⣄    ]],
                    [[          ⣸⣿⣿⢧ ⢻⠻⣿⣿⣷⣄⣀⠄⠢⣀⡀⠈⠙⠿⠄   ]],
                    [[         ⢠⣿⣿⣿⠈  ⠡⠌⣻⣿⣿⣿⣿⣿⣿⣿⣛⣳⣤⣀⣀  ]],
                    [[  ⢠⣧⣶⣥⡤⢄ ⣸⣿⣿⠘⠄ ⢀⣴⣿⣿⡿⠛⣿⣿⣧⠈⢿⠿⠟⠛⠻⠿⠄ ]],
                    [[ ⣰⣿⣿⠛⠻⣿⣿⡦⢹⣿⣷   ⢊⣿⣿⡏  ⢸⣿⣿⡇ ⢀⣠⣄⣾⠄  ]],
                    [[⣠⣿⠿⠛⠄⢀⣿⣿⣷⠘⢿⣿⣦⡀ ⢸⢿⣿⣿⣄ ⣸⣿⣿⡇⣪⣿⡿⠿⣿⣷⡄ ]],
                    [[⠙⠃   ⣼⣿⡟  ⠈⠻⣿⣿⣦⣌⡇⠻⣿⣿⣷⣿⣿⣿ ⣿⣿⡇⠄⠛⠻⢷⣄]],
                    [[     ⢻⣿⣿⣄   ⠈⠻⣿⣿⣿⣷⣿⣿⣿⣿⣿⡟ ⠫⢿⣿⡆    ]],
                    [[      ⠻⣿⣿⣿⣿⣶⣶⣾⣿⣿⣿⣿⣿⣿⣿⣿⡟⢀⣀⣤⣾⡿⠃    ]],
                    [[                                 ]],
                    [[                                 ]],
                    [[                                 ]],
                    [[                                 ]],
                    [[                                 ]],
                    [[                                 ]],
                    [[                                 ]],
                    [[                                 ]],
                },
                center = {
                    {
                        icon = "  ",
                        desc = "New File",
                        key = "n",
                        key_format = "[%s]",
                        action = "enew",
                    },
                    {
                        icon = "  ",
                        desc = "Find File",
                        key = "f",
                        key_format = "[%s]",
                        action = "Oil",
                    },
                    {
                        icon = "  ",
                        desc = "Load Session",
                        key = "l",
                        key_format = "[%s]",
                        action = "require('persistence').load()",
                    },
                    {
                        icon = "  ",
                        desc = "Load Previous Session",
                        key = "p",
                        key_format = "[%s]",
                        action = "require('persistence').load({last = true})",
                    },
                    {
                        icon = "  ",
                        desc = "Select Session",
                        key = "s",
                        key_format = "[%s]",
                        action = "require('persistence').select()",
                    },
                    {
                        icon = "  ",
                        desc = "Exit",
                        key = "q",
                        key_format = "[%s]",
                        action = "q",
                    },
                },
                footer = {
                    [[]],
                    [[some say there is no exit]],
                },
            },
            hide = {},
            preview = {},
        })
    end,
    dependencies = { { "nvim-tree/nvim-web-devicons" } },
}
